### ISSUE TITLE
NOt able to open

### ISSUE THREAD

**Issue by ghost** [faysal515/Java-Simple-Hotel-Management#1]
Hey, I needed help on how can I open the project. Can you please provide step by step process to open the project?

**Comment by faysal515** [comment]
if you have netbeans installed, then it should be one min task. open netbeans > open project and select the folder

**Comment by ghost** [comment]
Hi
There are some errors showing up when I run the project.
Can you please remove the errors?

**Comment by faysal515** [comment]
can you please send the error log and screenshot, please ?

**Comment by kranthi99** [comment]
Hi 
I am getting errors.

**Comment by kranthi99** [comment]
![screenshot 2](https://user-images.githubusercontent.com/35165047/36310150-2596a3f6-134d-11e8-9bd7-a50f8b91167e.png)

**Comment by faysal515** [comment]
I think jcalendar is undefined here. add this as project dependency and all the related files are in the lib folder
