### ISSUE TITLE
Refactorizacion Move Field e Inline Class

### ISSUE THREAD

**Issue by Jfede98** [faysal515/Java-Simple-Hotel-Management#10]
Hola note que habia un code smell en tu proyecto que usando tecnicas de refactorizacion se podria arreglar. Por tal motivo decidi hacerlo. Encontre el code smell Lazy Class
![image](https://user-images.githubusercontent.com/66968793/104848253-1bdfb200-58b2-11eb-8577-785625b526ab.png)
En la siguiente justificacion te dire el porque de este code smell: 
En este caso la clase Food quedo sin un uso especifico. Si bien existe una clase que pone las órdenes del cliente en el sistema de hotel, no hay un verdadero uso de la clase Food en general, ya que al pedir algún alimento usan un String o la clase Item que posee en si los mismos parámetros que la clase Food que no se usa. Lo que nos deja una clase vaga que se debió de haber tratado de usar, pero al terminar todo la implementación y codificación del proyecto quedo sin ninguna función. Por lo tanto, se pondrá los parámetros de esta clase con sus atributos en otra la cual será la clase Item. La clase Food será eliminada.
Usando la tecnica de Inline Class el codigo quedaria de la siguiente manera:
![image](https://user-images.githubusercontent.com/66968793/104848379-ae805100-58b2-11eb-91ad-70e27637979a.png)
![image](https://user-images.githubusercontent.com/66968793/104848382-b213d800-58b2-11eb-87f9-717142ef458d.png)

Hola note que habia un code smell en tu proyecto que usando tecnicas de refactorizacion se podria arreglar. Por tal motivo decidi hacerlo. Encontre el code smell Shotgun Surgery
![image](https://user-images.githubusercontent.com/66968793/104849683-16d23100-58b9-11eb-884f-add55b4ded0a.png)
En la siguiente justificacion te dire el porque de este code smell: 
En este caso sucede con la clase RoomFare, ya que al hacer una leve modificación en esta clase tendremos que realizar cambios en la clase Room, lo que hace que nuestro código no sea del todo eficiente. Realizar leves cambios en una clase y que esto nos obligue a realizar también cambios en otra clase se lo conoce como Shotgun Surgery. Por tal motivo se usar Move Field para mover los atributos de RoomFare a Room ahorrándonos este problema.
Usando la tecnica de Move Field el codigo quedaria de la siguiente manera:
![image](https://user-images.githubusercontent.com/66968793/104849706-2c475b00-58b9-11eb-9739-6c5f475f63c5.png)

**Comment by faysal515** [comment]
No tengo idea de que la gente esté usando este proyecto y dando comentarios para mejorar el código base. Si bien aprecio esta actitud, no tengo ninguna intención de mejorar esto desde que me mudé de Java en 2015. Pero si toman las iniciativas para refactorizar y enviar una solicitud de extracción, estaré feliz de fusionarme. Gracias.

Si encuentra que mi español es abusivo o incorrecto, culpe a Google. Usé su herramienta de traducción.

@Jfede98
