### ISSUE TITLE
Trabajo Diseño de Software - Implementación principios SOLID

### ISSUE THREAD

**Issue by aargudo1910** [faysal515/Java-Simple-Hotel-Management#5]
[Sugerencias.pdf](https://github.com/faysal515/Java-Simple-Hotel-Management/files/4951314/Sugerencias.pdf)

**Comment by faysal515** [comment]
No tengo idea de que la gente esté usando este proyecto y dando comentarios para mejorar el código base. Si bien aprecio esta actitud, no tengo ninguna intención de mejorar esto desde que me mudé de Java en 2015. Pero si toman las iniciativas para refactorizar y enviar una solicitud de extracción, estaré feliz de fusionarme. Gracias.

Si encuentra que mi español es abusivo o incorrecto, culpe a Google. Usé su herramienta de traducción.
