### ISSUE TITLE
Implementation of some solid principles

### ISSUE THREAD

**Issue by TomVilla** [faysal515/Java-Simple-Hotel-Management#6]
Hi, in a group work we did we have found parts in which the code could be improved, taking into account the SOLID principles, here I attach the document with some corrections that we made with the class diagram in the modified part.
[principles.docx](https://github.com/faysal515/Java-Simple-Hotel-Management/files/5578733/principles.docx)

**Comment by faysal515** [comment]
Please send a PR, and I'll merge it. I have no plan to work on this project as mentioned in the readme doc
