### ISSUE TITLE
Recomendación de Principio SOLID

### ISSUE THREAD

**Issue by paudpez14** [faysal515/Java-Simple-Hotel-Management#7]
Hola amigo como parte de un trabajo de Universidad estuve encomendado en revisar tu proyecto a ver si incumplía estos principios y darte solución de como arreglarlos.
Saludos.
Te adjunto un documento de como se podría arreglar.
[Principio SRP.docx](https://github.com/faysal515/Java-Simple-Hotel-Management/files/5578828/Principio.SRP.docx)

**Comment by faysal515** [comment]
No tengo idea de que la gente esté usando este proyecto y dando comentarios para mejorar el código base. Si bien aprecio esta actitud, no tengo ninguna intención de mejorar esto desde que me mudé de Java en 2015. Pero si toman las iniciativas para refactorizar y enviar una solicitud de extracción, estaré feliz de fusionarme. Gracias.

Si encuentra que mi español es abusivo o incorrecto, culpe a Google. Usé su herramienta de traducción.
