### ISSUE TITLE
Aplicacion de Patrones de Diseño

### ISSUE THREAD

**Issue by Jfede98** [faysal515/Java-Simple-Hotel-Management#8]
Hola, revisando tu proyecto me di cuenta que se podria mejorar al usar algunos patrones de diseño en algunas clases de tu proyecto. Te adjutare un documento con estas sugerencias. Cualquier duda me puedes preguntar, y en cualquier momento te explico.
[Expliacion de Iterator.docx](https://github.com/faysal515/Java-Simple-Hotel-Management/files/5765387/Expliacion.de.Iterator.docx)

**Comment by faysal515** [comment]
No tengo idea de que la gente esté usando este proyecto y dando comentarios para mejorar el código base. Si bien aprecio esta actitud, no tengo ninguna intención de mejorar esto desde que me mudé de Java en 2015. Pero si toman las iniciativas para refactorizar y enviar una solicitud de extracción, estaré feliz de fusionarme. Gracias.

Si encuentra que mi español es abusivo o incorrecto, culpe a Google. Usé su herramienta de traducción.
