### ISSUE TITLE
Técnicas de Refactorización 

### ISSUE THREAD

**Issue by tati-18** [faysal515/Java-Simple-Hotel-Management#9]
Inline Temp: 
En muchas partes del código  tiene variables temporales que se están usado solo una vez para ser retornada en el mismo momento, por ejemplo, Connection está ocupando espacio innecesario, es por esto que al usar Inline Temp eliminamos aquella variable y solo retornamos lo necesario.  Ejemplo:
![image](https://user-images.githubusercontent.com/59493650/104819785-ccd84500-57fd-11eb-8156-222f80464302.png)
Pull Up Method:
 los métodos FlushAll() y FlushStatmentOnly()  se repite en muchas clases  con las mismas funcionalidades, con la técnica Pull Up Method nos muestra que podemos mover los métodos a una clase independiente.
![image](https://user-images.githubusercontent.com/59493650/104819953-52a8c000-57ff-11eb-9341-6e332a8fe947.png)
Method Object:
Se tiene un método demasiado largo en el que las variables locales están entrelazadas por lo que no se pueden aplicar el método de extracción, con la tecnica de refactoring mencionada te  permitirá transformar el método en una clase separada para que las variables locales se conviertan en campos de la clase.

**Comment by faysal515** [comment]
No tengo idea de que la gente esté usando este proyecto y dando comentarios para mejorar el código base. Si bien aprecio esta actitud, no tengo ninguna intención de mejorar esto desde que me mudé de Java en 2015. Pero si toman las iniciativas para refactorizar y enviar una solicitud de extracción, estaré feliz de fusionarme. Gracias.

Si encuentra que mi español es abusivo o incorrecto, culpe a Google. Usé su herramienta de traducción.
